"""Add travelers table

Revision ID: 2ba76b9937bf
Revises: 8b3f6a1c2d4e
Create Date: 2026-09-05 11:28:08.657801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ba76b9937bf'
down_revision = '8b3f6a1c2d4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('travelers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tour_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tour_id'], ['tours.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('travelers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_travelers_tour_id'), ['tour_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('travelers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_travelers_tour_id'))

    op.drop_table('travelers')
    # ### end Alembic commands ###
